Add BYO notebook
cohere-ai/notebooks pull request #222
Opened 2024-09-27 20:03 UTC by youran-qi

Copy the BYO notebook from https://github.com/cohere-ai/cohere-aws/blob/main/notebooks/sagemaker/Deploy%20your%20own%20finetuned%20command-r-0824.ipynb to here

2024-09-30 13:42 UTC, kyle-cohere commented
Can you please replace the title header with an h2 instead of h1? (Use `##` instead of `#`). The compiler will think it's a python comment

2024-09-30 19:18 UTC, youran-qi commented
> Can you please replace the title header with an h2 instead of h1? (Use `##` instead of `#`). The compiler will think it's a python comment

OK. @kyle-cohere Done. See [here](https://github.com/cohere-ai/notebooks/pull/222/commits/f2cb81e58e82a608bc41aa5edc340ef980dd3594)

2024-09-30 21:00 UTC, CoderHam requested changes
Minor change else LGTM
Please test before merge?

2024-09-30 21:00 UTC, CoderHam commented on notebooks/finetuning/Deploy your own finetuned command-r-0824.ipynb
> +    "!pip install cohere>=5.11.0"
```suggestion
    "!pip install \"cohere>=5.11.0\""
```

2024-09-30 21:13 UTC, youran-qi commented on notebooks/finetuning/Deploy your own finetuned command-r-0824.ipynb
> +    "!pip install cohere>=5.11.0"
OK. Added. Thank you!

2024-09-30 21:45 UTC, CoderHam approved these changes

2024-10-01 09:46 UTC, kyle-cohere commented
Most recent changes were 12h ago so I'm assuming @youran-qi has had a chance to test this. Merging to unblock publication

2024-10-01 09:46 UTC, merged